//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo_ws_Blazor.Components.Pages
{
    public partial class Home
    {

        private PersonaViewModel persona { get; set; } = new();

        private void HandleSubmit()
        {
            Console.WriteLine($"Enviado: {persona.Nombre} con DNI: {persona.Dni}");
        }

        public class PersonaViewModel
        {
            public int Dni { get; set; }
            public string? Nombre { get; set; }
        }
    }
}